#!/bin/sh

mount sysfs
/sbin/mdev -s

# NIC up
ip link set lo up
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2

# mount all
mkdir dev/pts
mount -a

# telnet
telnetd -l ${LOGIN} &

# mount nfs
mount /mnt
