#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
/sbin/mdev -s

ln -sf /dev/null /dev/tty2
ln -sf /dev/null /dev/tty3
ln -sf /dev/null /dev/tty4

# NIC up
modprobe r8152
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2
ip link set lo up

# automatic start

# telnet
mkdir dev/pts
mount -t devpts devpts /dev/pts
telnetd -l ${LOGIN} &

# nfs
mount -t nfs -o nolock HOST_MACHINE:${HOST_PATH} /mnt
